### ISSUE TITLE
[ENH] Consider changing the default axis to 0

### ISSUE THREAD

**Issue by brunofacca** [simaki/fracdiff#73]
Hello. Thank you again for this great library.

When `fracdiff.fdiff` is given a Pandas DataFrame as input or a Pandas Dataframe converted to a NumPy array by calling `df.values`, the value of the `axis` parameter will default to `1`, which does not make sense for this use case as it would apply fractional differentiation across columns and each column contains a different variable. Given the popularity of Pandas, this behavior seems counter-intuitive. For example, I've spent several minutes trying to figure out why the output was not stationary as expected (it was because of this default). I'd like to suggest changing the default of value of the `axis` parameter to `0`.

**Comment by simaki** [comment]
Thank you so much for the suggestion!  That's quite reasonable.

Choosing `axis=0` makes great sense and one of the judicious choices among others.
The reason why `fdiff` uses `axis=-1` as default is to keep it as much consistent as possible with [`numpy.diff`](https://numpy.org/doc/stable/reference/generated/numpy.diff.html).
Sorry for the inconvenience, but I'd like to keep this consistency.

FYI, a sklearn-like transformer [`Fracdiff`](https://simaki.github.io/fracdiff/#fracdiff) may fit your preference as it differentiates along `axis=0`.

Again, thank you a lot for using this and making a great suggestion.
Any proposals for enhancement are more than welcome.

**Comment by brunofacca** [comment]
Hello,

I was unaware of NumPy's default of `axis=-1` and the intent to keep the interfaces consistent. In that case, the `axis=-1` default makes sense. 

Another possibility may be to add a warning about it to the documentation. I would even suggest having the method display a warning if given a 2D array such as a Pandas DataFrame or the resut of `pandas_df.values` as input and no user-defined value for the `axis` parameter, but I guess that would also differ from `numpy.diff`'s behavior, which may not be desirable.

Thanks again for all the work put into this library. It literally reduced the execution time of some of the most used functions in a project I'm working on from minutes to a few seconds.

Have a great weekend.

**Comment by simaki** [comment]
Thank you. I think we can now close this issue.
I hope good luck with your project.
Have a nice weekend!
