### ISSUE TITLE
BUG:  'numpy.ndarray' object has no attribute 'is_integer'

### ISSUE THREAD

**Issue by thistleknot** [simaki/fracdiff#79]
using python 3.9.4

fdiff(all_data.iloc[:, 1], n=d[[1]])

AttributeError                            Traceback (most recent call last)
<ipython-input-143-fbc829e193db> in <module>
----> 1 fdiff(all_data.iloc[:, 1], n=d[[1]])

/mnt/distvol/Python-3.9.4/lib/python3.9/site-packages/fracdiff/base.py in fdiff(a, n, axis, prepend, append, window, mode)
    113     """
    114     # Return `np.diff(...)` if n is integer
--> 115     if isinstance(n, int) or n.is_integer():
    116         return np.diff(a, n=int(n), axis=axis, prepend=prepend, append=append)
    117 

AttributeError: 'numpy.ndarray' object has no attribute 'is_integer'

**Comment by thistleknot** [comment]
nm


import numpy as np
from fracdiff import fdiff

a = np.array(all_data.iloc[:, 1])
fdiff(a, n=d[1])

**Comment by simaki** [comment]
Thank you for sharing that.
Could you let me know what's in `all_data` and `d`?  I want to reproduce that bug locally.

I guess `d[[1]]` and `d[1]` are numpy.array, not float/integer.

fyi: https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

**Comment by thistleknot** [comment]
Just data i was working with. Could use cars data set. I used arfima to
derive a d value...

Its in here, im using a dataset of electricity prices

https://github.com/thistleknot/Python-Stock/blob/master/RNN.ipynb

**Comment by thistleknot** [comment]
The github w the data for those prices
I then derived a mean of the 24 hour periods
https://github.com/Carterbouley/ElectricityPricePrediction

**Comment by simaki** [comment]
Thanks. 

The AttributeError for your snippet 
```py
fdiff(all_data.iloc[:, 1], n=d[[1]])
```
(or `fdiff(a, n=d[1])`) seems to imply that `d[[1]]` is numpy array while `fdiff` only accepts float/integer as `n`. Could you check `type(d[[1]])`?
